name: Matrix Testing
on: [push, pull_request]
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        gemfile: ['5.2', '6.0', '6.1', '7.0']
        ruby: ['2.7', '3.0', '3.1', '3.2']
        exclude:
          - gemfile: '5.2'
            ruby: '3.0'
          - gemfile: '5.2'
            ruby: '3.1'
          - gemfile: '5.2'
            ruby: '3.2'

    runs-on: ubuntu-latest
    env: # $BUNDLE_GEMFILE must be set at the job level, so it is set for all steps
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - run: bundle exec rspec
